In [1]:
#split():---------------------------------------------------------------------
import numpy as np
arr=np.array([1,2,3,4,5,6])

#split the array into 3 equal sized sub-arrays
sub_arrays=np.split(arr,3)

#print the sub-arrays
for sub_arr in sub_arrays:
    print(sub_arr)
    

[1 2]
[3 4]
[5 6]


In [3]:
#sort()-------- it is used to sort elements in an array
import numpy as np
arr=np.array([3,1,2,4,5])
sorted_arr=np.sort(arr)
print("sorted array (ascending):",sorted_arr)
sorted_arr_desc=np.sort(arr)[::-1]
print("sorted array (descending):",sorted_arr_desc)

sorted array (ascending): [1 2 3 4 5]
sorted array (descending): [5 4 3 2 1]


In [4]:
#sorting along specific axis:-----------------
import numpy as np
matrix=np.array([[3,1,2],[6,5,4]])
sorted_matrix=np.sort(matrix,axis=1)
print("sorted matrix (ascending along rows):")
print(sorted_matrix)

sorted matrix (ascending along rows):
[[1 2 3]
 [4 5 6]]


In [9]:
#numpy join-----np.vstack()==for vertical stacking,np.hstack()==dor horizontal stacking,concatenate()

#1) concatenate()

import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.concatenate((arr1,arr2),axis=1)   #here 1 means row
print(result)

print("-----------------------------------------------")
result2=np.concatenate((arr1,arr2),axis=0)   #here 0 means column
print(result2)

[[1 2 5 6]
 [3 4 7 8]]
-----------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
#2) vstack()

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("implementing vstack")
result=np.vstack((arr1,arr2))
print(result)
print("-----------------------------------------------")
print("implementing hstack")
result1=np.hstack((arr1,arr2))


print(result1)

implementing vstack
[[1 2 3]
 [4 5 6]]
-----------------------------------------------
implementing hstack
[1 2 3 4 5 6]


In [22]:
#standard deviation:------------------------------------
import numpy as np
# Score of Class A students
classA= np.array([85, 88, 90, 92, 95])

# Score of Class A students
classB= np.array([70, 80, 85, 95, 100])

#mean of classA
classA_mean=np.mean(classA)
print(classA_mean)
#variance of classA
classA_variance=np.var(classA)
print(classA_variance)
#standard deviation of classA
stdA=np.std(classA)
print(stdA)

print("--------------------------------------------------------------")
print("mean of classB")
classB_mean=np.mean(classB)
print(classB_mean)
print("varaince of class b")
var_b=np.var(classB)
print(var_b)
print("standard deviation of class b")
std_b=np.std(classB)
print(std_b)




90.0
11.6
3.40587727318528
--------------------------------------------------------------
mean of classB
86.0
varaince of class b
114.0
standard deviation of class b
10.677078252031311


In [23]:
#percentile:-----------------------------------------------------------

import numpy as np
# Test scores of 30 students
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138])
median = np.percentile(test_scores, 50)
print("Median (50th Percentile):", median)


Median (50th Percentile): 109.0


In [25]:
#percentile:--------------------------------------------------------------
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138])
median = np.percentile(test_scores, 25)
print("Median (25th Percentile):", median)


Median (25th Percentile): 95.25


In [27]:
#load():------------------------------------------------------
import numpy as np
scores=np.array([85,92,78,88,95,72,89])
np.save('student-scores.npy',scores)
loaded_scores=np.load('student_scores.npy')
print("original scores:",scores)
print("loaded scores:",loaded_scores)

<class 'FileNotFoundError'>: [Errno 44] No such file or directory: 'student_scores.npy'