In [3]:
#ques1:----------------------------
'''convert the below list into numpy array then display the array'''

import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)


[1 2 3 4 5]


In [4]:
#ques2:----------------------------
'''convert the below list into a numpy array then display the array then display the first and last index and
then multiply each element by 2 and display the result'''

import numpy as np
lst=[1,2,3,4,5]

# Convert list to numpy array
arr = np.array(lst)

# Display the array
print("Array:", arr)

# Display the first and last index
print("First index:", arr[0])
print("Last index:", arr[-1])

# Multiply each element by 2
arr_multiplied = arr * 2

# Display the result
print("Array after multiplication by 2:", arr_multiplied)



Array: [1 2 3 4 5]
First index: 1
Last index: 5
Array after multiplication by 2: [ 2  4  6  8 10]


In [5]:
#ques3:----------
'''write a numpy program to create an array of 10 zeros,10ones and 10 fives'''

import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)
print("Array of 10 zeros:", zeros_array)

# Create an array of 10 ones
ones_array = np.ones(10)
print("Array of 10 ones:", ones_array)

# Create an array of 10 fives
fives_array = np.full(10, 5)
print("Array of 10 fives:", fives_array)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [6]:
#ques4:----------------
'''write a numpy program to create a 3*3 matrix with values ranging from 2 to 10'''

import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values ranging from 2 to 10:")
print(matrix)



3x3 matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
